- name: Ensure deployment directory exists
  file:
    path: "./echoserver"
    state: directory
    mode: '0755'

- name: Generate docker-compose.yml for Echo Server
  template:
    src: "{{ playbook_dir }}/roles/echoserver/templates/docker-compose.yml.j2"
    dest: "{{ project_src_path }}/docker-compose-echoserver.yml"
    mode: '0644'

