---
- hosts: localhost
  become: true
  vars:
    nginx_server_count: 2
    echo_server_count: 2
    project_src_path: /usr/local/bin/haproxy-poc/

  tasks:
    - name: Include Nginx role
      import_role:
        name: nginx

    - name: Include Echo Server role
      import_role:
        name: echoserver

    - name: Include HAProxy role
      import_role:
        name: haproxy

    - name: Deploy Nginx services with scaling
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-nginx.yml
        state: restarted
        scale:
          nginx: "{{ nginx_server_count }}"

    - name: Deploy Echo Server services with scaling
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-echoserver.yml
        state: restarted
        scale:
          echoserver: "{{ echo_server_count }}"

    - name: Deploy HAProxy services
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-haproxy.yml
        state: restarted