---
- hosts: localhost
  become: true
  vars:
    nginx_server_count: 8
    echo_server_count: 8
    project_src_path: /usr/local/bin/haproxy-poc/

  tasks:
    - name: Include Nginx role
      import_role:
        name: nginx

    - name: Include Echo Server role
      import_role:
        name: echoserver

    - name: Include HAProxy role
      import_role:
        name: haproxy

    - name: Restart NGINX Containers 
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-nginx.yml
        state: restarted

    - name: Restart Echo Server Containers 
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-echoserver.yml
        state: restarted

    - name: Restart HAProxy Container
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-haproxy.yml
        state: restarted

    - name: Scale Nginx Conatiners
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-nginx.yml
        state: present
        scale:
          nginx: "{{ nginx_server_count }}"

    - name: Scale Echo server Containers
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}"
        files:
          - docker-compose-echoserver.yml
        state: present
        scale:
          echoserver: "{{ echo_server_count }}"


